name: Send Daily Motivational Quotes

on:
  schedule:
    # 每周五、六、日 UTC 2:00 (北京时间 10:00)
    - cron: "0 2 * * 5,6,0"
  workflow_dispatch: # 允许手动触发

jobs:
  send-quote:
    runs-on: ubuntu-latest
    env:
      ALAPI_TOKEN: ${{ secrets.ALAPI_TOKEN }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      PGP_PUBLIC_KEY: ${{ secrets.PGP_PUBLIC_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-gnupg

      - name: Run quote sender
        run: python scripts/send_quote.py
